apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-foyer
  labels:
    app: app-foyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-foyer
  template:
    metadata:
      labels:
        app: app-foyer
    spec:
      containers:
      - name: app-foyer
        image: onsfadhel/tpfoyeresprit:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://10.106.69.167:3306/foyer_db?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: "update"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.MySQLDialect"
        ports:
        - containerPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: app-foyer
spec:
  selector:
    app: app-foyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: NodePort  # Change to LoadBalancer if you need external access
