apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-datavolume-foyer
spec:
  capacity:
    storage: 1Gi  # La taille doit correspondre à celle du PVC
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
